QSHOP/QSHOP/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('goods/',include('goods.urls',namespace='goods')),
    path('user/',include('user.urls',namespace='user')),
    path('manager/',include('manager.urls',namespace='manager')),

]

QSHOP/goods/urls.py
from django.urls import path
urlpatterns = [
    # path=()
]

app_name = 'goods'

QSHOP/manager/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('index/',views.index,name="index"),
    path('base/',views.base,name="base"),
    path('register/',views.register,name="register"),
    path('check_username/',views.check_username,name = "check_username"),
    path('login/',views.login,name="login"),
    path('logout/',views.logout,name="logout"),
    path('add_goods/',views.add_goods,name="add_goods"),

]

app_name = 'manager'

QSHOP/user/urls.py
from django.urls import path
urlpatterns = [
    # path=()
]

app_name = 'user'

QSHOP/goods/models.py
from django.db import models
from manager.models import Type,Manager
# Create your models here.

class Goods(models.Model):
    class Meta():
        verbose_name="商品"
        verbose_name_plural="商品"
    goods_name=models.CharField(max_length=50,verbose_name='商品名称')
    goods_opice = models.FloatField(verbose_name='现价')
    goods_xprice=models.FloatField(verbose_name='原价')
    goods_count=models.IntegerField(default=0,verbose_name='商品数量')
    goods_production=models.DateField(auto_now=True,verbose_name='生产日期')
    safe_date = models.CharField(max_length=10,verbose_name='保质期')
    goods_method=models.CharField(max_length=100,verbose_name="存储方法")
    goods_description = models.CharField(max_length=100,verbose_name='商品简介')
    goods_pic=models.ImageField(upload_to='media/goods/image',verbose_name='商品图片')
    goods_addresss = models.CharField(max_length=50,verbose_name='配送地址')
    goods_info = models.TextField(verbose_name='商品详情')
    manager = models.ForeignKey(Manager,on_delete=models.CASCADE,verbose_name='商家名称')
    type=models.ForeignKey(Type,on_delete=models.CASCADE,verbose_name='类别')
    status=models.BooleanField(default=1,verbose_name='商品状态')
    def __str__(self):
        return self.goods_name

QSHOP/manager/models.py
from django.db import models

# Create your models here.
class Type(models.Model):
    class Meta():
        verbose_name = "商品类型"
        verbose_name_plural = "商品类型"
    type_name = models.CharField(max_length=50,verbose_name = '商品类别名称')
    date = models.DateTimeField(auto_now_add = True,verbose_name = '更新时间')
    def __str__(self):
        return self.type_name


class Manager(models.Model):
    class Meta():
        verbose_name = "商家"
        verbose_name_plural = "商家"
    manager_name = models.CharField(max_length=50,verbose_name='商家姓名')
    email = models.EmailField("商家邮箱")
    password = models.CharField(max_length=32,verbose_name="商家密码")
    image = models.ImageField(upload_to='media/manage/image',default="https://source.unsplash.com/QAB-WJcbgJk/60x60")
    is_login = models.BooleanField(default=0)

QSHOP/user/models.py
from django.db import models

# Create your models here.

QSHOP/goods/views.py
from django.shortcuts import render

# Create your views here.

QSHOP/manager/views.py
from django.shortcuts import render,HttpResponseRedirect,HttpResponse
from  QSHOP.common import set_password
from .models import Manager,Type
import json
from django.http import JsonResponse
from goods.models import Goods


# Create your views here.
def base(request):
    return render(request,'manage_base.html')

def index(request):
    manager_name = request.session.get("manager_name")
    # id = request.session["id"]
    manager=request.COOKIES.get("manager")
    print(manager_name,manager,id)
    if manager_name and manager:
        return render(request,'common/index.html')
    else:
        return HttpResponseRedirect('/manager/login')


def register(request):
    error = ""
    if request.method == "POST":
        data = request.POST
        name = data.get('name')
        email = data.get('email')
        password = data.get('password')
        repeat_password = data.get('repeat_password')
        print(name,email,password,repeat_password)
        if password != repeat_password:
            error = "两次密码不一致"
            return render(request, 'common/register.html', {'error': error})
        md5_pwd = set_password(set_password(password))
        m=Manager.objects.filter(manager_name=name)
        if not m.exists():
            m=Manager.objects.create(manager_name=name,email=email,password=md5_pwd)
            print(m,type(m))
            return HttpResponseRedirect('/manager/login')
        error = "用户名重复"
    return render(request,'common/register.html',{'error':error})

def check_username(request):
    result = {"flag":0}
    data = request.GET
    username = data.get("username")
    print(username)
    if username != "":
        m = Manager.objects.filter(manager_name=username)
        if not m.exists():
            result["flag"] = 1
        # message= "用户名重复"
    return HttpResponse(json.dumps(result))

def login(request):
    error=""
    if request.method=="POST":
        data = request.POST
        manager_name = data.get("username")
        password = data.get("password")
        # print(manager_name,password)
        md5_pwd = set_password(set_password(password))
        # print(md5_pwd)
        try:
            m = Manager.objects.get(manager_name=manager_name,password=md5_pwd)
            #设置session
            request.session['manager_name'] = manager_name
            request.session['id'] = m.id
            #设置cookie
            response = HttpResponseRedirect('/manager/index')
            response.set_cookie("manager",manager_name)
            return response
        except:
            error = "用户名密码有误"

    return render(request,'common/login.html',{'error':error})

def logout(request):
    request.session.clear()
    response = HttpResponseRedirect('/manager/login')
    response.delete_cookie('manager')
    return response


def add_goods(request):

    manager_name = request.session.get("manager_name")
    # id = request.session["id"]
    manager = request.COOKIES.get("manager")
    if manager_name and manager:
        if request.method == "POST":
            data = request.POST
            goods_name = data.get("goods_name")
            goods_opice = data.get("goods_opice")
            goods_xprice = data.get("goods_xprice")
            goods_count = data.get("goods_count")
            goods_production = data.get("goods_production")
            safe_date = data.get("safe_date")
            goods_method = data.get("goods_method")
            goods_description = data.get("goods_description")
            goods_pic = request.FILES.get('goods_pic')
            goods_addresss = data.get("goods_addresss")
            goods_info = data.get("goods_info")
            manager_id = request.session.get("id")
            type = data.get("type")
            status = data.get("status")

            Goods.objects.create(
                goods_name=goods_name,
                goods_opice=goods_opice,
                goods_xprice=goods_xprice,
                goods_count=goods_count,
                goods_production=goods_production,
                safe_date=safe_date,
                goods_method=goods_method,
                goods_description=goods_description,
                goods_pic=goods_pic,
                goods_addresss=goods_addresss,
                goods_info=goods_info,
                manager_id=manager_id,
                type_id=type,
                # type=Type.objects.get(id=type),
                status=status,
            )
            return HttpResponse("商品添加成功")
    else:
        return HttpResponseRedirect('/manager/login')

    type_list = Type.objects.all()
    return render(request,'common/add_goods.html',{"type_list":type_list})

QSHOP/user/views.py
from django.shortcuts import render

# Create your views here.

QSHOP/manager/templates/common/add_goods.html
{% extends 'manage_base.html' %}

{% load static %}

{% block title %}

{% endblock %}

{% block content %}
    <form action="{% url 'manager:add_goods' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <p>
            <input type="text" class="form-control"  placeholder="商品名称"  false   maxlength="50" name="goods_name">
        </p>

        <p>
            <input type="number" class="form-control"  placeholder="现价"  false  name="goods_opice">
        </p>
        <p>
            <input type="number" class="form-control"  placeholder="原价"  false  name="goods_xprice">
        </p>

         <p>
            <input type="number" class="form-control"  placeholder="商品数量"  false    name="goods_count">
        </p>

         <p>
            <input type="date" class="form-control"  placeholder="生产日期"  false    name="goods_production">
        </p>

         <p>
            <input type="text" class="form-control"  placeholder="保质期"  false   maxlength="10" name="safe_date">
        </p>

        <p>
            <input type="text" class="form-control"  placeholder="存储方法"  false   maxlength="100" name="goods_method">
        </p>

        <p>
            <input type="text" class="form-control"  placeholder="商品简介"  false   maxlength="100" name="goods_description">
        </p>

        <p>
            <input type="file" class="form-control"  placeholder="商品图片"  false   name="goods_pic">
        </p>

        <p>
            <input type="text" class="form-control"  placeholder="配送地址"  false   maxlength="50" name="goods_addresss">
        </p>

        <p>
            <select name="type" id="type" class="form-control" false>
                <option value="0">---请选择---</option>
                {% for type in type_list %}
                    <option value="{{ type.id }}">{{ type.type_name }}</option>
                {% endfor %}
            </select>
        </p>

        <p>
            <label class="radio-inline">
                <input type="radio" name="status" id="0" value=0>上架
            </label>
            <label class="radio-inline">
                <input type="radio" name="status" id="1" value=1>下架
            </label>
        </p>

        <p>
            <textarea name="goods_info" id="goods_info"></textarea>
        </p>
        <button class="btn btn-primary">提交</button>
    </form>
{% endblock %}

{% block script %}
    <script src="/static/ckeditor/ckeditor/ckeditor.js"></script>
    <script>
        CKEDITOR.replace("goods_info",{uiColor:'#c9cddf'})
    </script>
{% endblock %}

QSHOP/manager/templates/common/login.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>登录页面</title>

  <!-- Custom fonts for this template-->
  <link href="/static/manager/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="/static/manager/css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">欢迎登录</h1>
                  </div>
                  <form class="user" method="post">
                      {% csrf_token %}
                    <div class="form-group">
                      <input type="text" class="form-control form-control-user" id="exampleInputEmail" aria-describedby="emailHelp" placeholder="请输入账号" name="username">
                    </div>
                    <div class="form-group">
                      <input type="password" class="form-control form-control-user" id="exampleInputPassword" placeholder="请输入密码" name="password">
                    </div>
                    <div style="color: red;font-size: 14px">{{ error }}</div>
                    <input type="submit"  class="btn btn-primary btn-user btn-block" value="登录">

                    <hr>

                  </form>
                  <hr>
                  <div class="text-center">
                    <a class="small" href="#">忘记密码</a>
                  </div>
                  <div class="text-center">
                    <a class="small" href="{% url 'manager:register' %}">创建一个账号</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="/static/manager/vendor/jquery/jquery.min.js"></script>
  <script src="/static/manager/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Core plugin JavaScript-->
  <script src="/static/manager/vendor/jquery-easing/jquery.easing.min.js"></script>

  <!-- Custom scripts for all pages-->
  <script src="/static/manager/js/sb-admin-2.min.js"></script>

</body>

</html>

QSHOP/manager/templates/common/register.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>注册页面</title>

  <!-- Custom fonts for this template-->
  <link href="/static/manager/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="/static/manager/css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

  <div class="container">

    <div class="card o-hidden border-0 shadow-lg my-5">
      <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row">
          <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
          <div class="col-lg-7">
            <div class="p-5">
              <div class="text-center">
                <h1 class="h4 text-gray-900 mb-4">创建账号</h1>
              </div>
              <form class="user" action="" method="post">
                  {% csrf_token %}
                <div class="form-group ">

                    <input type="text" class="form-control form-control-user" id="exampleFirstName" placeholder="用户名"  name="name" required onblur="check_username()">


                </div>
                <div class="form-group">
                  <input type="email" class="form-control form-control-user" id="exampleInputEmail" placeholder="Email Address" name="email">
                </div>
                <div class="form-group row">
                  <div class="col-sm-6 mb-3 mb-sm-0">
                    <input type="password" class="form-control form-control-user" id="exampleInputPassword" placeholder="Password" name="password">
                  </div>
                  <div class="col-sm-6">
                    <input type="password" class="form-control form-control-user" id="exampleRepeatPassword" placeholder="Repeat Password" name="repeat_password">
                  </div>
                </div>
                  {% if error %}
                  <div style="color: red;">{{ error }}</div>
                  {% endif %}
                  <input class="btn btn-primary btn-user btn-block" value="注册" required disabled type="submit" id="submit">


              </form>
              <hr>
              <div class="text-center">
                <a class="small" href="#">忘记密码</a>
              </div>
              <div class="text-center">
                <a class="small" href="{% url 'manager:login' %}">已有账户,去登录</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="/static/manager/vendor/jquery/jquery.min.js"></script>
  <script src="/static/manager/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Core plugin JavaScript-->
  <script src="/static/manager/vendor/jquery-easing/jquery.easing.min.js"></script>

  <!-- Custom scripts for all pages-->
  <script src="/static/manager/js/sb-admin-2.min.js"></script>

  <script>
      var username = document.getElementById('exampleFirstName');
      console.log(1111);
      console.log(1111111111111,username.value);
      var user = $('#exampleFirstName');
      console.log(2,user);
      var user = $('input[name="username"]');
      console.log(3,user);
      var user = $('.username');
      console.log(4,user);

      function check_username(){
          var user =$('input[name="name"]').val();
          console.log(user);


          $.ajax({
              url:'{% url "manager:check_username" %}',
              data:{username:user},
              dataType:'json',
              type:'get',
              success:function (data) {
                  console.log(data);
                  if (data.flag == 1){
                      $('#submit').attr('disabled',false)
                  }
                  else{
                      window.alert('用户名重复')
                  }
              },
              error:function (message) {

              }
      })}



  </script>
</body>


</html>